version: '3'

volumes:
  db_data:

services:
  postgres:
    image: postgres:13.2
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'

  app:
    build: .
    stdin_open: true
    tty: true
    command: ["bin/run"]
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/simplefoods